### ISSUE TITLE
Double / potentially confusing connection errors

### ISSUE THREAD

**Issue by Raicuparta** [Bwc9876/ow-mod-man#68]
### What Happened?

Running the manager while offline.

This one shows up twice (shows again right after first pressing ok). The error might be a big confusing for non-technical people, but they should probably still be able to guess that it means connection error.
![image](https://github.com/Bwc9876/ow-mod-man/assets/3955124/81de11f8-acf8-42c0-bd93-805c5fba8a60)

This one is a bit worse, but unlikely to happen in practice (could happen during GitHub outages though). Happens when trying to install OWML on first launch. Two messages pop up at the same time but look slightly different. The message might be very confusing since it implies that a database *was* found, but owml isn't there.
![image](https://github.com/Bwc9876/ow-mod-man/assets/3955124/2332eeeb-557c-48c0-ad8d-9c9332910692)

### Package

Graphical Interface

### Platform

Linux

**Comment by Bwc9876** [comment]
First one happening twice is probably because you're running in dev and the effect to refresh the db is running twice, I agree on the error message for both needing to be more descriptive though.

**Comment by Bwc9876** [comment]
Ok so I'm changing the remote refresh message to display in the remote mods tab instead of in a dialog and say "No mods found in the database, check your network connection and database URL" 

And the owml setup will say "There was an error downloading OWML, please check your network connection and try again". Also making it only display once bc I forgot to pass false to the command to make it not show an error dialog in addition to the one I'm showing :P.
